(load "rulesAireAcondicionado.clp")
(load "rulesCalefaccion.clp")
(load "rulesEmergencia.clp")
(load "rulesIluminacion.clp")
(load "rulesMovimiento.clp")
(load "rulesRacks.clp")
(load "rulesSensores.clp")
(load "rulesVentilador.clp")